locations:
  dataIn: ~/local/pure3d/client/input
  dataOut: ~/local/pure3d/client/dist
  partialsIn: «base»/p3d/components
  templates: «base»/p3d/templates
  images: «base»/p3d/images
  js: «base»/p3d/js
  cssIn: «base»/p3d/css/input-p3d.css
  cssOut: ~/local/pure3d/client/dist/css/style.css

markdown:
  keys:
    - abstract
    - description
    - provenance
